### PR TITLE
Test for new automation

### PR DESCRIPTION
**Pull request by ElijahCaine**

### CODE REVIEW

**Comment by ElijahCaine** [comment]
!bump major # Update a cookbook from version 0.2.32 to 1.0.0

**Comment by ElijahCaine** [comment]
!bump major production

**Comment by ElijahCaine** [comment]
!bump major production # Update cookbook from version 0.2.32 to 1.0.0

**Comment by ElijahCaine** [comment]
!bump major production

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.2.32.  Have a nice day!

**Pull request merged**
